name: Deploy to Hugging Face Space

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          set -e

          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          echo "Cloning HF Space..."
          git clone https://oauth2:$HF_TOKEN@huggingface.co/spaces/1c34/live-api hf-space

          cd hf-space

          echo "Syncing files via git (clean replace)..."

          rsync -av \
            --delete \
            --exclude='.git' \
            --exclude='hf-space' \
            ../ .

          git add -A
          git commit -m "deploy" --allow-empty
          git push